// Mocks generated by Mockito 5.4.6 from annotations
// in warshity/test/features/clients/presentation/cubit/clients_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:warshity/features/clients/data/data_source/clients_remote_data_source.dart'
    as _i2;
import 'package:warshity/features/clients/data/model/customer_model.dart'
    as _i5;
import 'package:warshity/features/clients/data/repo/clients_reprosatory.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeClientsRemoteDataSource_0 extends _i1.SmartFake
    implements _i2.ClientsRemoteDataSource {
  _FakeClientsRemoteDataSource_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ClientsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockClientsRepository extends _i1.Mock implements _i3.ClientsRepository {
  MockClientsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ClientsRemoteDataSource get remoteDataSource =>
      (super.noSuchMethod(
            Invocation.getter(#remoteDataSource),
            returnValue: _FakeClientsRemoteDataSource_0(
              this,
              Invocation.getter(#remoteDataSource),
            ),
          )
          as _i2.ClientsRemoteDataSource);

  @override
  _i4.Stream<List<_i5.CustomerModel>> watchClients() =>
      (super.noSuchMethod(
            Invocation.method(#watchClients, []),
            returnValue: _i4.Stream<List<_i5.CustomerModel>>.empty(),
          )
          as _i4.Stream<List<_i5.CustomerModel>>);

  @override
  _i4.Stream<_i5.CustomerModel> watchClient(String? clientId) =>
      (super.noSuchMethod(
            Invocation.method(#watchClient, [clientId]),
            returnValue: _i4.Stream<_i5.CustomerModel>.empty(),
          )
          as _i4.Stream<_i5.CustomerModel>);

  @override
  _i4.Future<void> addClient(_i5.CustomerModel? client) =>
      (super.noSuchMethod(
            Invocation.method(#addClient, [client]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> decreaseDebt({
    required String? clientId,
    required num? amount,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#decreaseDebt, [], {
              #clientId: clientId,
              #amount: amount,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> increaseDebt({
    required String? clientId,
    required num? amount,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#increaseDebt, [], {
              #clientId: clientId,
              #amount: amount,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeClient(String? clientId) =>
      (super.noSuchMethod(
            Invocation.method(#removeClient, [clientId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
