// Mocks generated by Mockito 5.4.6 from annotations
// in warshity/test/features/add_invoice/presentation/cubit/invoice_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:warshity/features/add_invoices/data/data_source/add_invoice_remote_data.dart'
    as _i2;
import 'package:warshity/features/add_invoices/data/repo/add_invoice_repository.dart'
    as _i3;
import 'package:warshity/features/invoices/data/models/invoice_model.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeInvoicesRemoteDataSource_0 extends _i1.SmartFake
    implements _i2.InvoicesRemoteDataSource {
  _FakeInvoicesRemoteDataSource_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [InvoicesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockInvoicesRepository extends _i1.Mock
    implements _i3.InvoicesRepository {
  MockInvoicesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.InvoicesRemoteDataSource get remoteDataSource =>
      (super.noSuchMethod(
            Invocation.getter(#remoteDataSource),
            returnValue: _FakeInvoicesRemoteDataSource_0(
              this,
              Invocation.getter(#remoteDataSource),
            ),
          )
          as _i2.InvoicesRemoteDataSource);

  @override
  _i4.Future<void> createInvoice(_i5.InvoiceModel? invoice) =>
      (super.noSuchMethod(
            Invocation.method(#createInvoice, [invoice]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> finalizeInvoice(_i5.InvoiceModel? invoice) =>
      (super.noSuchMethod(
            Invocation.method(#finalizeInvoice, [invoice]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<List<_i5.InvoiceModel>> watchInvoices() =>
      (super.noSuchMethod(
            Invocation.method(#watchInvoices, []),
            returnValue: _i4.Stream<List<_i5.InvoiceModel>>.empty(),
          )
          as _i4.Stream<List<_i5.InvoiceModel>>);

  @override
  _i4.Future<_i5.InvoiceModel?> getInvoice(String? invoiceId) =>
      (super.noSuchMethod(
            Invocation.method(#getInvoice, [invoiceId]),
            returnValue: _i4.Future<_i5.InvoiceModel?>.value(),
          )
          as _i4.Future<_i5.InvoiceModel?>);

  @override
  _i4.Future<void> checkStock(_i5.InvoiceModel? invoice) =>
      (super.noSuchMethod(
            Invocation.method(#checkStock, [invoice]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteInvoice(String? invoiceId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteInvoice, [invoiceId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<List<_i5.InvoiceModel>> watchClientInvoices(String? customerId) =>
      (super.noSuchMethod(
            Invocation.method(#watchClientInvoices, [customerId]),
            returnValue: _i4.Stream<List<_i5.InvoiceModel>>.empty(),
          )
          as _i4.Stream<List<_i5.InvoiceModel>>);

  @override
  _i4.Stream<List<_i5.InvoiceModel>> watchAllClientInvoices(
    String? customerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchAllClientInvoices, [customerId]),
            returnValue: _i4.Stream<List<_i5.InvoiceModel>>.empty(),
          )
          as _i4.Stream<List<_i5.InvoiceModel>>);
}
