// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtm0pPwbuK2f9KbFie3WGLx-mQUCg5_FA',
    appId: '1:861319834330:web:69984e62bc53bd82d493e3',
    messagingSenderId: '861319834330',
    projectId: 'warshity-75dcf',
    authDomain: 'warshity-75dcf.firebaseapp.com',
    storageBucket: 'warshity-75dcf.firebasestorage.app',
    measurementId: 'G-M0JTL41C6W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0tgDQ5CkGg8xcufRMCXBorBoecLZOUM8',
    appId: '1:861319834330:android:4399d58d640a5e19d493e3',
    messagingSenderId: '861319834330',
    projectId: 'warshity-75dcf',
    storageBucket: 'warshity-75dcf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8VDj5iWXterYCuptj-HNuvdHX_-3167I',
    appId: '1:861319834330:ios:be5b75c2f3b8cdd3d493e3',
    messagingSenderId: '861319834330',
    projectId: 'warshity-75dcf',
    storageBucket: 'warshity-75dcf.firebasestorage.app',
    iosBundleId: 'com.example.warshity',
  );
}
