// Mocks generated by Mockito 5.4.6 from annotations
// in warshity/test/features/products/presentation/cubit/add_products_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i4;
import 'dart:typed_data' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:warshity/features/products/data/datascource/products_remote_data_source.dart'
    as _i2;
import 'package:warshity/features/products/data/models/product_model.dart'
    as _i5;
import 'package:warshity/features/products/data/repo/products_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeProductsRemoteDataSource_0 extends _i1.SmartFake
    implements _i2.ProductsRemoteDataSource {
  _FakeProductsRemoteDataSource_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProductsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductsRepository extends _i1.Mock
    implements _i3.ProductsRepository {
  MockProductsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ProductsRemoteDataSource get remoteDataSource =>
      (super.noSuchMethod(
            Invocation.getter(#remoteDataSource),
            returnValue: _FakeProductsRemoteDataSource_0(
              this,
              Invocation.getter(#remoteDataSource),
            ),
          )
          as _i2.ProductsRemoteDataSource);

  @override
  _i4.Stream<List<_i5.ProductModel>> watchProducts() =>
      (super.noSuchMethod(
            Invocation.method(#watchProducts, []),
            returnValue: _i4.Stream<List<_i5.ProductModel>>.empty(),
          )
          as _i4.Stream<List<_i5.ProductModel>>);

  @override
  _i4.Future<String> uploadProductImage(
    _i6.Uint8List? imageBytes,
    String? imageName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadProductImage, [imageBytes, imageName]),
            returnValue: _i4.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#uploadProductImage, [imageBytes, imageName]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<void> addProduct(_i5.ProductModel? product) =>
      (super.noSuchMethod(
            Invocation.method(#addProduct, [product]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteProduct(String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProduct, [productId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> increaseProductQuantity(String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#increaseProductQuantity, [productId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> decreaseProductQuantity(String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#decreaseProductQuantity, [productId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setProductQuantity({
    required String? productId,
    required int? quantity,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setProductQuantity, [], {
              #productId: productId,
              #quantity: quantity,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
