// Mocks generated by Mockito 5.4.6 from annotations
// in warshity/test/features/accountsharing/presentation/cubit/account_sharing_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:warshity/features/account_sharing/data/data_source/account_sharing_remote_data_source.dart'
    as _i2;
import 'package:warshity/features/account_sharing/data/models/share_invitation_model.dart'
    as _i5;
import 'package:warshity/features/account_sharing/data/repositories/account_sharing_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAccountSharingRemoteDataSource_0 extends _i1.SmartFake
    implements _i2.AccountSharingRemoteDataSource {
  _FakeAccountSharingRemoteDataSource_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

/// A class which mocks [AccountSharingRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccountSharingRepository extends _i1.Mock
    implements _i3.AccountSharingRepository {
  MockAccountSharingRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AccountSharingRemoteDataSource get remoteDataSource =>
      (super.noSuchMethod(
            Invocation.getter(#remoteDataSource),
            returnValue: _FakeAccountSharingRemoteDataSource_0(
              this,
              Invocation.getter(#remoteDataSource),
            ),
          )
          as _i2.AccountSharingRemoteDataSource);

  @override
  _i4.Future<void> sendInvitation({required String? email}) =>
      (super.noSuchMethod(
            Invocation.method(#sendInvitation, [], {#email: email}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<List<_i5.ShareInvitationModel>> watchReceivedInvitations() =>
      (super.noSuchMethod(
            Invocation.method(#watchReceivedInvitations, []),
            returnValue: _i4.Stream<List<_i5.ShareInvitationModel>>.empty(),
          )
          as _i4.Stream<List<_i5.ShareInvitationModel>>);

  @override
  _i4.Stream<Map<String, String>> watchSentInvitationStatuses() =>
      (super.noSuchMethod(
            Invocation.method(#watchSentInvitationStatuses, []),
            returnValue: _i4.Stream<Map<String, String>>.empty(),
          )
          as _i4.Stream<Map<String, String>>);

  @override
  _i4.Future<void> respondToInvitation({
    required String? invitationId,
    required bool? accept,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#respondToInvitation, [], {
              #invitationId: invitationId,
              #accept: accept,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getActiveSharedAccounts() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveSharedAccounts, []),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Stream<List<Map<String, dynamic>>> watchActiveSharedAccounts() =>
      (super.noSuchMethod(
            Invocation.method(#watchActiveSharedAccounts, []),
            returnValue: _i4.Stream<List<Map<String, dynamic>>>.empty(),
          )
          as _i4.Stream<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<String>> getActiveConnectionIds() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveConnectionIds, []),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
          )
          as _i4.Future<List<String>>);

  @override
  _i4.Stream<List<String>> watchActiveConnectionIds() =>
      (super.noSuchMethod(
            Invocation.method(#watchActiveConnectionIds, []),
            returnValue: _i4.Stream<List<String>>.empty(),
          )
          as _i4.Stream<List<String>>);

  @override
  _i4.Future<List<String>> getConnectedUserIds() =>
      (super.noSuchMethod(
            Invocation.method(#getConnectedUserIds, []),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
          )
          as _i4.Future<List<String>>);

  @override
  _i4.Stream<List<String>> watchConnectedUserIds() =>
      (super.noSuchMethod(
            Invocation.method(#watchConnectedUserIds, []),
            returnValue: _i4.Stream<List<String>>.empty(),
          )
          as _i4.Stream<List<String>>);

  @override
  _i4.Future<List<String>> getConnectionMembers(String? connectionId) =>
      (super.noSuchMethod(
            Invocation.method(#getConnectionMembers, [connectionId]),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
          )
          as _i4.Future<List<String>>);

  @override
  _i4.Future<void> deleteSharedAccount(String? connectionId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSharedAccount, [connectionId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getSharedAccountId() =>
      (super.noSuchMethod(
            Invocation.method(#getSharedAccountId, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Stream<String?> watchSharedAccountId() =>
      (super.noSuchMethod(
            Invocation.method(#watchSharedAccountId, []),
            returnValue: _i4.Stream<String?>.empty(),
          )
          as _i4.Stream<String?>);
}
